### ISSUE TITLE
Bundling instead of downloading

### ISSUE THREAD

**Issue by Enchufa2** [ericdunipace/RcppCGAL#5]
Is there any reason why `inst/include` is in `.Rbuildignore`? It would be better to just ship that directory, as e.g. BH does, and avoid an additional download at install time.

**Comment by ericdunipace** [comment]
As you intuit, there is a reason. First, it would entail changing the file names or structures for the header files to comply with CRAN policies on portability, and second, the package size then raises a warning that CRAN maintainers also weren't happy about. BH gets around these by altering the file names and also gets an exception on the package size, probably because Dirk is the author. You can always download from the GitHub here.

**Comment by Enchufa2** [comment]
Because you tried to submit it and got it rejected due to the size? Because, AFAIK, 1) it's a NOTE, not a WARNING, and 2) the issues raised by CRAN have to do with the size of docs, not libraries or includes. There's e.g. https://cran.r-project.org/package=cgal4h, and that's not Dirk's.

The reason I'm raising this is because automatic downloads at install time are generally regarded as a bad practice. At the very least, it could be a security hole. And that's why Internet access is forbidden at install time by Linux distros. This kind of packages fails to install without additional intervention of downstream maintainers ([example](https://copr.fedorainfracloud.org/coprs/iucar/cran/package/R-CRAN-RcppCGAL/)), and therefore it is less likely that your package is included in our repositories.

Yes, users can always download it from here, but by putting it on CRAN, I assume you want it to be easy to use and redistribute. All I say is that, by not shipping the whole codebase in the same tarball, you are making redistribution harder. Hope it helps.

**Comment by ericdunipace** [comment]
Sorry, it seems like you missed it from above, but let me say it again: shipping the code base in the same tarball *is not possible* without renaming and reorganizing the header files, which I have not wanted to do. 

Also, I am aware of the cgal4h package but for some reason they rejected my package even though it was smaller in size. Faulty inductive logic does not change this fact. 

 I imagine you are frustrated since it sounds like you've had trouble installing the package, but rather than working constructively to solve the issue together, you have responded quite rudely. 

Installation of the tarball *is* possible if you follow the instructions by linking your library of CGAL to the package. If that doesn't work, please raise an issue with your R version, your OS, and the errors you are receiving. As always, please write with respect and kindness to others. Hope this helps.

**Comment by ericdunipace** [comment]
Permanently resolved via update 5.6.0 pending CRAN approval
